### ISSUE TITLE
Data Entry Bug

### ISSUE THREAD

**Issue by maia-fw** [DrOgres/electric-state#22]
### Issues with data entry in the Journey tab

[https://www.loom.com/share/45adbde2948d4d6787c908fb203b94f1?sid=9fbbb6eb-6b58-49f5-9cb3-02a95efb54cd](https://www.loom.com/share/45adbde2948d4d6787c908fb203b94f1?sid=9fbbb6eb-6b58-49f5-9cb3-02a95efb54cd)

**Comment by DrOgres** [comment]
fixed in 0.5.0
