### ISSUE TITLE
Unable to adjust numbers on Vehicle sheet

### ISSUE THREAD

**Issue by maia-fw** [DrOgres/electric-state#23]
### Unable to adjust numbers with arrows on Vehicle sheet

<img width="768" alt="Screenshot 2024-10-08 at 14 42 43" src="https://github.com/user-attachments/assets/5fe67515-c964-418f-997b-62469894b0ab">

**Comment by maia-fw** [comment]
Would be great to be able to do it for: 
- Maneuverability
- Speed
- Hull
- Armor
- Fuel
- Passenger

**Comment by DrOgres** [comment]
fixed in 0.5.0
