### ISSUE TITLE
Text block / responsive issues

### ISSUE THREAD

**Issue by maia-fw** [DrOgres/electric-state#25]
### On the PC character sheet, there seems to be this issue where the cursor starts somewhere in the middle of the text block area.
<img width="683" alt="Screenshot 2024-10-14 at 19 10 01" src="https://github.com/user-attachments/assets/3a9100da-f701-4244-a6c3-1440e8c83061">
<img width="735" alt="Screenshot 2024-10-14 at 19 10 28" src="https://github.com/user-attachments/assets/7f9501a8-bb0b-4d98-a14f-e02a277f6f40">

---

### Some responsive issues on the Main tab for Vehicles. Names are getting cutoff at a certain width. 
<img width="764" alt="Screenshot 2024-10-14 at 19 10 43" src="https://github.com/user-attachments/assets/6a20ec02-65ee-425d-a6fe-b283015c2137">

**Comment by DrOgres** [comment]
> ### On the PC character sheet, there seems to be this issue where the cursor starts somewhere in the middle of the text block area.
> <img alt="Screenshot 2024-10-14 at 19 10 01" width="683" src="https://private-user-images.githubusercontent.com/125773658/376420839-3a9100da-f701-4244-a6c3-1440e8c83061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTYxODcsIm5iZiI6MTcyODk1NTg4NywicGF0aCI6Ii8xMjU3NzM2NTgvMzc2NDIwODM5LTNhOTEwMGRhLWY3MDEtNDI0NC1hNmMzLTE0NDBlOGM4MzA2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMTMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2JlNjU2NmI5MDkwZWMzZTZjNTBjNDgwZGI0OTM0OGFiMzZiYWNkNTMwNmZjMTUzY2I4ZWFmMWI4OTE4YzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-1PX-vWXsaLbOnegka7h74gsSzB_mMgh4-JfBEzLwaY"> <img alt="Screenshot 2024-10-14 at 19 10 28" width="735" src="https://private-user-images.githubusercontent.com/125773658/376420865-7f9501a8-bb0b-4d98-a14f-e02a277f6f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTYxODcsIm5iZiI6MTcyODk1NTg4NywicGF0aCI6Ii8xMjU3NzM2NTgvMzc2NDIwODY1LTdmOTUwMWE4LWJiMGItNGQ5OC1hMTRmLWUwMmEyNzdmNmY0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMTMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmYxOTBjMDk1NjBmN2Q3MjlmNDcxYTgxMTRlMjA2ZTdiNTVmZDM2MWFkNGE5NGVkN2YxYmY3ODQ0YjI1OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kWWyvHWe8s_WzCqmGMXNPql7ojM3nUP8HhyNDk8HtKU">


This is a quirk of text area HTML elements, if they are not truly empty they behave in very odd ways (one reason I lean on input fields by instinct) I'll se what I can do to mitigate this but some strange behavior is kind of baked into the element.  

I changed the passenger list to make names slightly longer but to also gracefully ellipsis at the end rather than overflow onto other elements, will be up in the next update

**Comment by DrOgres** [comment]
test this in v0.9.0 and let me know your thoughts I coded custom input fields to help it should be better than the old. If so I'll replace some of the other fields as well

thanks!
