### ISSUE TITLE
Image Token Width is Squished

### ISSUE THREAD

**Issue by maia-fw** [DrOgres/electric-state#33]
The default image width is squished. Small issue, just wondering if that could be fixed. 

![Screenshot 2024-11-04 at 20 46 34](https://github.com/user-attachments/assets/72988858-ae12-433c-8d1e-884126016022)
![Screenshot 2024-11-04 at 20 47 07](https://github.com/user-attachments/assets/37dcba35-149a-4dd3-a327-3a2b97b20b79)
![Screenshot 2024-11-04 at 20 47 23](https://github.com/user-attachments/assets/e3ef841b-8e32-4581-ba4b-f9b5fe8e12a7)
![Screenshot 2024-11-04 at 20 47 44](https://github.com/user-attachments/assets/a395eb3b-4d8d-42ce-90c3-27fa56d5ab9c)
![Screenshot 2024-11-04 at 20 47 50](https://github.com/user-attachments/assets/d65f0f3d-bfa5-43f9-900a-b001c16d80b6)

**Comment by DrOgres** [comment]
fixed in 0.21.0
