### ISSUE TITLE
Players cannot edit Tension entries and delete existing data.

### ISSUE THREAD

**Issue by KaiderWeise** [DrOgres/electric-state#34]
When a player tries to create another character for Tension, the player has no options in the drop-down menu. The field is empty. As an SL, I can select any character there. 
If the players go into an entry I have created as an GM via Edit to describe the tension, unfortunately the selected name disappears and the entry remains gone. 
Happens via browser (Chrome) and also via Foundry App.
Unfortunately, this means that the entries for Tension cannot be used. 

The first image is from GM´s point of view. The second from the player's point of view.

![tension 1](https://github.com/user-attachments/assets/84560d62-f8a1-4a32-9431-1ca2abad9e76)
![Tension 2](https://github.com/user-attachments/assets/2fa8bf15-d28c-49eb-a927-f10ad221cfe1)

**Comment by DrOgres** [comment]
This is related to #30 

Your players must have at least limited access to all actors that they can have tension with.  This prevents actors such as NPCs Robots etc. from showing up in the list.  I do plan on updating the UI to improve clarity on this but you must set up the actors for them to have Limited Permission for any they do not own.  

Note that there are Limited actor sheets to prevent players from seeing information about other characters they would not know.

**Comment by DrOgres** [comment]
Closing this.  If current changes to the implementation in v0.22.0 do not provide the needed functionality or provide enough clarity on how this feature works I will revisit it later.  feel free to open a new issue should that be the case.
